sudo: required
dist: xenial
language: cpp
compiler:
  - gcc
python:
  - "3.7"
# Change this to your needs
before_install:
  - sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev libopenmpi1.10
script:
  - make clean
  - make all
  - make cleantest
  - make tests
  - make runtests

